### ISSUE TITLE
The VoteRandom Wiki page is messed up

### ISSUE THREAD

**Issue by SamDaMan1** [Person8880/Shine#499]
The mode order is wrong.

Here is the copy paste from the coding: 

Plugin.MODE_RANDOM = 1
Plugin.MODE_SCORE = 2
Plugin.MODE_ELO = 3
Plugin.MODE_KDR = 4
Plugin.MODE_HIVE = 5

Here is your wiki:
1.Pure random.

2. Hive recorded score per minute played. Anyone with no past score on record or with a past score of 0 is randomised.

3. NOTE: NS2Stats is no more, so this mode no longer functions. NS2Stats Elo ranking based. This obviously requires NS2Stats to be installed. It will use the Elo ranking saved for each player from NS2Stats to place players with a stored Elo ranking evenly between the teams, then use the fallback method to sort the remaining players that do not have a ranking stored.

4. Past KDR based. Same as the score based, except it uses each player's Hive recorded kill to death ratio to balance the teams. Anyone with a past KDR of 0 is randomised. Assists count for 10 percent of a kill.

5. Using the game's built in skill ranking. This ranking is tracked in some servers and is a fairly reliable data source for balancing. However, the game sometimes has issues getting the ranking data and may leave everyone with a 0 skill rank. This is a problem with the game, not Shine. This mode is not available in NS2: Combat.

**Comment by SamDaMan1** [comment]
Also, which mode do you recommend to use? I've been trying mode 2 and 5 but I am not sure which one is better..

**Comment by Person8880** [comment]
Umm, the orders are identical, aren't they?

1. Random
2. Score (note Hive score per minute played is not Hive skill)
3. NS2Stats Elo (which no longer works)
4. KDR (using Hive's recorded kills, deaths and assists, again not skill)
5. Hive skill, which is what the wiki page displays.

What's the difference you're seeing (other than your issue containing two entries for number 1, which is not what's on the wiki page)?

As for which is better, the skill value (mode 5) *should* be the best, but there are numerous flaws in the underlying data at the moment which might throw it off (e.g. returning players with 1000 skill that don't represent 1000 skill). Otherwise, score per minute would be the next best for team contribution, while KDR is a better measure of individual player ability.

**Comment by SamDaMan1** [comment]
2 and 5 are mixed up, 2 is 5 and 5 is 2

**Comment by Person8880** [comment]
That's not correct. 2 is Hive recorded **score per minute**, while 5 is Hive **skill value**. The wiki is correct.

**Comment by SamDaMan1** [comment]
Ah, I see. My apologies for being stupid. I was also wondering, how do you seperate users in the user config? I couldn't find an explanation anywhere?

"Users":{
      "60577393 25142502":{
        "Group":"Member"
      }
    }

How do you seperate the 2 steam ID's?

**Comment by Person8880** [comment]
Each user should be a distinct key-value pair in the table. So like this:
```json
"Users": {
  "60577393": {
    "Group": "Member"
  },
  "25142502": {
    "Group": "Member"
  }
}
```

**Comment by SamDaMan1** [comment]
Ohhh I see! Thank you :D
