### ISSUE TITLE
Make it possible to grant users access to "sv_*" commands via shine

### ISSUE THREAD

**Issue by GhoulofGSG9** [Person8880/Shine#515]
Not all vanilla server admin commands have equivalent shine commands. 

So it would be nice if it would be possible to use the shine permission system to grant access to those as well.

**Comment by Person8880** [comment]
Is upvalue setting still a problem in the engine? Do I have to worry about changing an upvalue of an event hook function, or can I do that without it crashing now?

That's the only way I can see of doing this without repeating the entire vanilla command system.

**Comment by GhoulofGSG9** [comment]
The crash was fixed however every time you use `debug.setupvalue` the the LuaJit trace cache get's flushed.

So avoid using it frequently as it will have a direct impact on the performance.

If there are some vanilla function that should be global (or moved into the given class tables) instead of local to make it easier to access them just send me the diff of the needed changes and I'll try to get it into the next vanilla build.

**Comment by Person8880** [comment]
Yep, I'm aware of the performance implications of it along with the rest of the debug library. I just wanted to make sure the game won't explode if I use it.

As for the change to make it easier, it would be a trivial case of changing (in `ServerAdmin.lua`):
```lua
local function GetClientCanRunCommand(client, commandName, printWarning)
```
into
```lua
function GetClientCanRunCommand(client, commandName, printWarning)
```
so I can just overwrite the global instead of catching each command as they're registered to alter the upvalue.

**Comment by GhoulofGSG9** [comment]
The change will be part of the upcoming patch.
