### ISSUE TITLE
Bug in the AFK plugin 

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#573]
People who are spectating are occasionally kicked by the AFK plugin even though they are not AFK.
[AFKkick.json](https://www.dropbox.com/s/k3ddwrp28zy6yx8/AFKKick.json?dl=0)
It seems like it plugin doesn't always detect spectator activity.

**Comment by Person8880** [comment]
This is not necessarily a bug.

A spectator may very well not be AFK physically, but they may be stationary in terms of camera when watching the game. They could either be in first person spectate (which suppresses all input from the spectator) or be just leaving the camera watching without moving for a while.

As far as the server is concerned, both these cases are idle time, and thus if a spectator sits in these states for too long they'll be kicked. The only thing I can really do without spending way too much effort on these edge cases is to make movement in spectate significantly reduce the accumulated idle time compared to how it would normally reduce on a playing team. This change will be in the next update.

**Comment by SupaFred** [comment]
This can happen even when you pan around in overview spectate mode. It
doesn't always happen though and I'm trying to figure out what input isn't
detected properly. Moving the mouse to the sides of the screen to pan and
pressing space to change spectator mode should register.

**Comment by Person8880** [comment]
It's definitely tracking overview panning, pressing space, and any free camera movement (either just rotating the view or moving around). The only time input is not registered is first person spectate.

The most likely cause I can think of for being kicked even when not completely idle is simply not moving around enough to counteract accumulated idle time. That's why I increased the amount of time regained for spectator movement.

**Comment by SupaFred** [comment]
Isn't it a timer that gets set to 0 when it detects activity? If not then I
have misunderstood how it works.

**Comment by Person8880** [comment]
That's how it used to work a long time ago. However, that was changed to track idle vs active time.

Essentially, for as long as a player is idle their idle time will increase. When activity is detected, the idle time is reduced for the amount of time active, multiplied by a small factor to weight activity more than inactivity. Thus, a player who becomes active again does not immediately reset their AFK state. They have to be active for a significant time in order to go back to 0 AFK time.

The reason for this was to stop people from essentially sitting idle and moving their mouse slightly every few minutes. This method means that doing that would only gain them a second or two more time against the clock before being kicked.

**Comment by SupaFred** [comment]
I see. In that case I think the AFK plugin is working as intended. May I
request an option to use the old mode for AFK detection? The new mode isn't
suitable for spectator slots.

**Comment by Person8880** [comment]
It shouldn't be necessary for it to go back to the old system now. 1 second of active time for a spectator results in a 20 second reduction of idle time. You would assume a spectator will be moving around at least a little bit in a 20 second timespan, and the more they move the more time they regain (e.g. if they moved for 5 seconds that would be 1 minute and 40 seconds off the clock).

If that's still not enough I could expose the multiplying factor for spectators as a configuration option so you could increase it further, but going too far can allow people to get away with being essentially AFK as was the problem with the original method.

**Comment by SupaFred** [comment]
It's common for spectators to spectate someone for many minutes without any
input. To change spectator mode only requires one keypress which means that
the counter won't be reduced by much and they will be kicked despite
actively watching the game. The new way to detect AFK works well for
players but not for spectators.

**Comment by Person8880** [comment]
I've added a new option, `LenientModeForSpectators`, which when set to`true` will mean that spectator movement resets AFK time back to 0.

**Comment by SupaFred** [comment]
Thanks a lot! It will make the spectator guys on my servers very happy :)
