### ISSUE TITLE
nomination logic is misinterpreting lastmaps history

### ISSUE THREAD

**Issue by lancehilliard** [Person8880/Shine#585]
With ```"ExcludeLastMaps": {
    "Min": 3,
    "Max": 4
  }``` configuration, Shine is persisting a lastmaps.json file that's many more than that (```["ns2_gorge","ns2_mineshaft2","ns2_caged","ns2_biodome","ns2_descent","ns2_docking","ns2_nothing","ns2_tow_veil","ns2_veil","ns2_mesh","ns2_tgns_arclight","ns2_kodiak","ns2_mineral","ns2_hera","ns2_nexus","ns2_dark","ns2_tow_summit","ns2_refinery","ns2_tram","ns2_summit","ns2_eclipse"]```), such that maps which should be in rotation aren't.

**Comment by stickz** [comment]
@lancehilliard This is intended because it orders all the maps in server rotations from most to least recently played. With new map voter logic, this is a more efficient way to exclude maps. This is required because it's unpredictable how many maps the voter will need to exclude. In some cases, it could be a lot if max is 0.

Your `lastmaps.json` file doesn't have any impact on which maps you choose to be in server rotations. Is there anther bug you're experiencing with the map voter? What is your `maxoptions ` value set to?

**Comment by lancehilliard** [comment]
MaxOptions is 6. In the context of the lastmaps.json above, nominating ns2_caged gives the following error: "ns2_caged was recently played and cannot be voted for yet." I'd expect that error only if ns2_caged was one of the 3 (or 4?) recent maps.

**Comment by stickz** [comment]
The recent update to the shine map voter broke the nomination feature. I think this is what you're after, not the fact that `lastmaps.json` is handling the map exclusion process differently. The is intended the right thing to expect, but I don't think nominations are indexing through the ordered lists of maps properly.

**Comment by Person8880** [comment]
Apologies, I completely missed the fact that the nominate command checks the previous map list directly. Should be fixed and published in a few minutes.
