### ISSUE TITLE
Ping tracker kick people when server performance decrease/lag

### ISSUE THREAD

**Issue by BenjaminJacobs1** [Person8880/Shine#593]
The ping tracker should be auto-disabled if the average ping of all players reach some excessive level due to server side lag or server performance issue.

**Comment by Person8880** [comment]
This would be a symptom fix. I'm not keen on adding what would essentially be a hack to try and guess if there's a performance problem or not when the real fix would be to not have a performance problem.

**Comment by stickz** [comment]
A formula like this one could produce pretty accurate results for measuring ping data.
`Ping Change = Mean Ping * 0.6 + Median Ping * 0.4`

Pooling this every five seconds and averaging it out over a minute should detect a server issue long before the ping tracker starts kicking people. This shouldn't change by more than 30% in a minute.

**Comment by Person8880** [comment]
That's still a symptom fix. The problem is there's a performance problem, not that the ping tracker is kicking people.

If a server cannot maintain adequate performance then the ping tracker is going to be useless anyway, as it's correctly pointing out that everyone is going to be lagging behind/warping around.
