### ISSUE TITLE
Format string injection on !csay command

### ISSUE THREAD

**Issue by Katzenfleisch** [Person8880/Shine#595]
!csay %s (display a timer)
!csay %n (crash clients)

Might be other injections on the code, could be worse it to check them.

**Comment by Person8880** [comment]
The fact that `string.format` can crash anyone is concerning by itself. It should not be able to do that. In fact, it seems that the real problem is that any Lua error in a network receiver causes the game to crash.

Regardless, I'll disable formatting on csay messages, as it's not really intended to work anyway.
