### ISSUE TITLE
CheckGameStart causing intermittent comm-less game starts?

### ISSUE THREAD

**Issue by lancehilliard** [Person8880/Shine#597]
After NS2 314's release, TGNS games started suddenly force-starting without any commanders, after a seemingly random number of players joined teams. This new defective behavior only occurred intermittently (between occurrences, many games started normally, as expected). I was able to remove the unexplained force-start behavior entirely by commenting out only lines 105-109 of the following extension:

https://github.com/lancehilliard/TGNS/blob/968150cc4fa381d2ce87160c506cb8de5737bb17/mods/tgns/output/lua/shine/extensions/timedstart.lua#L105-L109

With these lines commented out, games always start normally, after both teams had commanders.

I don't know what causes the 314 games to suddenly force-start without commanders when the lines above are live, but I can say it seems to have started when NS2 314 was released -- of course, that doesn't necessarily mean a 314 change is to blame -- I don't know what's to blame -- it might be my other mod code in some way I don't understand (seems unlikely given how strongly correlated the defective behavior is to the lines above, which have worked great for months before 314) -- but I would argue I otherwise haven't changed any relevant code recently.

If there's a better way to prevent game starts when there are two commanders (105-109's intended purpose), please advise.

Regardless, how do I author extension code such that I can prevent game starts despite two commanders and such that games never force-start suddenly with zero commanders?

**Comment by Person8880** [comment]
This is due to a sort of bug/oversight in 314.

They made a change to make coming out of warm up mode move the game state to `PreGame`, whereas before it went to `NotStarted`. `PreGame` is the state that will cause the game to start after the pregame time has expired (see `NS2Gamerules:UpdatePregame`).

Your hook blocking `CheckGameStart` means it never sees if there are not 2 commanders, and thus the game eventually starts just because warm up turned off.

Really, the fix needs to be in NS2's code to make `WarmUp` transition to `NotStarted` rather than `PreGame`. I've [worked around it](https://github.com/Person8880/Shine/blob/master/lua/shine/extensions/pregame/server.lua#L598) in the `pregame` plugin for now by overriding `NS2Gamerules:UpdateWarmUp`.

Alternatively, make your `CheckGameStart` code transition the gamerules state to `NotStarted` whenever there are not 2 commanders.
