### ISSUE TITLE
Nominating a map when criteria are not met

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#624]
Scenario: A player nominates a map into the next map pool using sh_nominate . Now some of my maps have the criterias "max". and "min". Often players get confused when they nominate a map but the map will not be displayed in the next mapvote, but it says as message: You have nominated ns2_map.

Optimally a message should popup when nomitating the map displaying the min. and max. info or do not allow to nominate a map when min. and max. criteria are not met.

**Comment by Laaas** [comment]
If you're up for it, what about a new parameter for maps like "disabled", which causes it not to show in the map vote, but not show an error message when you nominate it?
This way you can silently disable maps.

**Comment by Person8880** [comment]
The reason it does not prevent players from nominating maps that don't fit the min/max player counts is that the number of players can change between the nomination time and the time the vote starts. The min/max are evaluated at the point the vote starts only.

If people are confused about the nomination then they just have to understand that a nomination is not a guarantee of it being chosen. I'm not sure there's much use in telling them exactly why it won't show up, especially because there are quite a few combinations of restrictions that could stop it (a min and no max, a max and no min etc.)

As for a disable option, I'm not sure I see the benefit in intentionally deceiving players when their choice would never actually make it into the vote.

**Comment by Laaas** [comment]
Thanks for the clarification!
That was mostly a joke about removing veil FYI, I'm really tired of that
map.
