### ISSUE TITLE
Improve vote concede algorithm?

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#630]
**I have a few suggestions to improve the vote concede algorithm.**

1.  Allow a higher vote concede percentage in the first X number of minutes. This logic could potentially be more effective than simply disabling voting for X number of minutes. Set a -1 value for disabled.

2. Create a configurable option to allow the blocking of concede votes when the last hive or command station has low health. This could allow the winning team to finish and remove lame concedes.

3. Create a configurable option to allow the commander to have two votes instead of one. Disabled by default. This could help curve issues with forced conceding (recycling), caused by voting thrustation.

**Comment by Person8880** [comment]
I've implemented the first 2 you've suggested.

1. Set `PercentNeededInEarlyGame` to a non-zero value to enable voting during the `VoteDelay` time with this percentage instead of the normal one.
2. Set `LastCommandStructureMinHealthPercent` to a value between 0 and 1 to decide how much health the last command structure has to have greater-equal than to allow a surrender vote.

For your third suggestion, I think there's too many edge cases to make this work well. Commanders could drop out or swap, and then that leaves it ambiguous as to who has their vote count for 2, not to mention adds more complexity for something that probably won't make much of a difference.
