### ISSUE TITLE
web bans list dissapearing from the server

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#641]
ok I posted an issue before where the ban list wouldn't download properly and that the list would go blank on the server

so I noticed a issue with the web server , I set the chgmod to 777 on the files and folder on the web server and its been working for a while fine, then say after a week or 2 the ban list was blank again on the game server so I check the ftp and the permissions on the files has changed to 644,

so I'm wondering would this cause the server to write a blank config or the other way round ??
also should the webserver be able to change the file permissions ?

please help as I lost the ban list again

**Comment by Person8880** [comment]
The PHP script sets the permissions:

```php
chmod($filename, 0664); //Normalise permissions
```

But this should be fine. `644` means public access is read-only (`4` is read-only, public is the last number), which should be sufficient to read from outside. The script doesn't overwrite this file anyway, it's actually making a new file each time that is a copy with the submitted ban/unban, and renaming the old file to have `.Old.json` at the end.

Do you know if the content of the file on the web-server is correct?

**Comment by fazmond** [comment]
yer as I said it holds the ban list for days fine but once the bans disappears they file is empty and the permssions are 644

**Comment by fazmond** [comment]
was also wondering if you could make this plugin to be able to write to a MySQL data base instead of a text file ?

**Comment by Person8880** [comment]
I've updated the [script here](https://github.com/Person8880/Shine/wiki/Bans#web-api-example) to avoid it wiping the data if it receives concurrent ban/unban requests. I'd assume that is the reason it's ended up blank.

As for MySQL, NS2 has no way to interact with it. The only way for NS2 to communicate with the outside world is HTTP requests. It would be possible to make a PHP script or otherwise that could manage bans with a MySQL server triggered by the current HTTP requests, but I don't really have the time to write such a thing.

**Comment by fazmond** [comment]
ok m8 will check this script and see how it goes
