### ISSUE TITLE
Improve rtv on mapvoting

### ISSUE THREAD

**Issue by stickz** [Person8880/Shine#643]
Could "MinPlayers" be changed to the number of players required to **_pass_** a map vote, instead of **_start_**?

I want to require 5 votes to change the map on my game-server, but I can't with a 51% pass ratio without preventing it from starting with at-least 9 players. This worsens my server configuration.

**Comment by Person8880** [comment]
This has been implemented in 93ebb3dee4f987a413c52681724941c0d6d07995.

Instead of changing the meaning of `MinPlayers`, I've removed it, `PercentToStart` and `PercentToFinish` in favour of a new `Constraints` config:
```json
"Constraints":{
    "MapVote":{
        "MinVotesRequired":{
            "Type":"Absolute",
            "Value":0
        },
        "MinVotesToFinish":{
            "Type":"Percent",
            "Value":0.8
        }
    },
    "NextMapVote":{
        "MinVotesRequired":{
            "Type":"Absolute",
            "Value":0
        },
        "MinVotesToFinish":{
            "Type":"Percent",
            "Value":2
        }
    },
    "StartVote":{
        "MinPlayers":{
            "Type":"Absolute",
            "Value":10
        },
        "MinVotesRequired":{
            "Type":"Percent",
            "Value":0.6
        }
    }
}
```
Essentially, `StartVote.MinPlayers` replaces the old `MinPlayers`, `StartVote.MinVotesRequired` replaces `PercentToStart`, and `MapVote.MinVotesToFinish` replaces `PercentToFinish`. The other settings allow for the extra control you wanted, i.e. the ability to set a pass constraint on each vote.

Values can be either `Absolute` or `Percent`, so the above example requires 10 players to start a map vote, and 60% of the server population to vote before it begins. If 80% of the population vote then the map vote will finish early and so on.
