### ISSUE TITLE
AFK Plugin false results

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#646]
The AFK Plugin seems to falsely detect active players and marks them as AFK. I have been sent multiple complaints of players doing something (actively playing) and get suddenly moved to the readyroom (With the warning message in chat). This should not be. It doesn't happen with everyone it seems.

**Comment by Person8880** [comment]
The warning message can't show up unless the server's received no input from them for >= the warn time. So either something's blocking the plugin from seeing input (a rogue mod perhaps), or their activity is not counted as input.

**Comment by Wooza42** [comment]
So the AFK plugin is really acting weird. Yet there is players sent to readyroom even tho they are moving and playing the game. I have seen it myself various times. It happens now since some time and only with one person on the server. Most times it's fine

Also it seems sometimes the plugin doesn't do anything at all and doesn't move AFK players into the ready room. I have two screenshots attached which proves it: The players "Mr_Funkyman" and "Brooklyn Chase" have both not moved at all during the round and are still on the server after 6 minutes. I can assure that they havn't moved at all, the posititon was the whole game the same, the face always looked in the same direction. 

![20171208235110_1](https://user-images.githubusercontent.com/19150896/33788764-3c799cfa-dc74-11e7-8496-942f538effbc.jpg)
![20171208235115_1](https://user-images.githubusercontent.com/19150896/33788767-3fa42c06-dc74-11e7-9561-4963c798d56f.jpg)


My AFKKick.json

{
    "Delay":1,
    "IgnoreSpectators":true,
    "KickOnConnect":false,
    "KickTime":5,
    "KickTimeIsAFKThreshold":0.5,
    "LenientModeForSpectators":true,
    "MarkPlayersAFK":false,
    "MinPlayers":50,
    "MoveToReadyRoomOnWarn":true,
    "MoveToSpectateOnWarn":false,
    "MovementDelaySeconds":0,
    "NotifyOnWarn":true,
    "OnlyCheckOnStarted":true,
    "Warn":true,
    "WarnMinPlayers":50,
    "WarnTime":2.5,
    "__Version":"1.6"
  }

**Comment by Person8880** [comment]
Your second screenshot shows 49 players in the server, and your config says the minimum number of players is 50, so that's why it's done nothing in that case.

As for it moving players into the ready room, I have no way to reproduce it. It has to be something else blocking the `OnProcessMove` event from firing, or messing with the contents of the player's input. In a completely vanilla game it never misses input when a player moves around.

There will be some extra logging available in the next release that you can enable with `"LogLevel": "Debug"` in the plugin's config which will log when the plugin warns a player and how long it thinks they were AFK for.

**Comment by Wooza42** [comment]
Thanks Person8880!

One more question: How does the plugin behave with people joining and leaving the server? Let's say there were 50 players, then 48, then again 50. Will the plugin reset the timer when the player amount goes below the minplayer?

**Comment by Person8880** [comment]
At the moment it resets as soon as the player count drops below the minimum.

**Comment by Wooza42** [comment]
I tried adding the new AFK feature:

"WarnActions": {
        "NoImmunity": [ "NOTIFY", "MOVE_TO_READY_ROOM" ],
        "PartialImmunity": [ "NOTIFY", "MOVE_TO_SPECTATE" ]
    }

But after a mapswitch the setting is removed

**Comment by Person8880** [comment]
It should have automatically converted the old config settings the first time it ran with the new plugin. Did it not do that for you?

**Comment by Wooza42** [comment]
No, it keeps reverting it. The version still says: 1.6

**Comment by Person8880** [comment]
Sounds like the mod's not actually updated on your server. As far as I can tell it's definitely published correctly, so maybe something is preventing your server from reaching the Steam Workshop to update it?

**Comment by Wooza42** [comment]
Sorry it was my bad. One of the server ops had to run a Shine Version with the temporary "NetworkUpdate" fix. thanks for solving the issue 👍

**Comment by Wooza42** [comment]
Ok so far so good, everything seem to run well despite of one remaing problem:

I have seen that people which are AFK often get shuffled into a team, even tho they did not do any input. Some time ago, AFK's were exluced by the vote, so weren't moved. The config is the same from above, despite I changed "WarnMinPlayers":50, to 42.

I can't find any option that is related to voterandom and afk plugin

**Comment by Person8880** [comment]
That's due to the fact all AFK time is reset when there are less than `WarnMinPlayers` on the server, so as far as the shuffle knows, no one is AFK.

**Comment by Person8880** [comment]
The next release is going to change the behaviour so that AFK time is always tracked, regardless of whether the minimum players are present or not.

That should allow shuffling to know who is AFK without having to lower any minimum player thresholds. It also means that as soon as there are the minimum number of players to start warning, anyone who has been AFK for long enough to be warned will be warned immediately, and same for kicking.
