### ISSUE TITLE
Plugin.CheckConfig not updating server config with new DefaultConfig

### ISSUE THREAD

**Issue by tsKenneth** [Person8880/Shine#652]
Hi, I have a Plugin.DefaultConfig in my code and Plugin.CheckConfig is also set to true. However, when I add a new field to Plugin.DefaultConfig, the plugin config file on the server does not add the new field even though the field does not exist. 

I have changed the plugin version number as well and the console log also says that "[01:27:50]Updating shinecredits config from version 2.8.0 to 2.9..." but the field is still missing after updating. I have also immediately saved the config after loading the config, fearing that the update was only on the cache.

Am I using this wrong or missing some steps? Please help and thank you.

**Comment by Person8880** [comment]
Is the new field nested in a sub-table? The current config check is a bit limited in that it avoids checking tables recursively, mostly because nested tables could be arrays or lookups whose keys don't have to follow the default config exactly.

I can add new functionality that's a little smarter that enables checking recursively while ignoring array values and tables that are explicitly marked as ignored in the default config if that's the case. It would be sat behind a new `CheckConfigRecursively` flag to avoid breaking existing plugins.

**Comment by tsKenneth** [comment]
Yes, unfortunately the new field is nested 3 levels deep. I used nested arrays for better presentation of the configurations enhance readability for server operators. A functionality like that would help alot! Thanks :)

**Comment by Person8880** [comment]
This has now been released. Give it a try and see if it does what you wanted.
