### ISSUE TITLE
Spectator Eating Res Slots

### ISSUE THREAD

**Issue by fazmond** [Person8880/Shine#666]
ok so I don't know if you been following discord ive been saying about problems with the reserved/player slots disappearing

so my server run (22playerslots +2reservedslots)total 24  + 4 official spec slots
the problem I have is the server can be 10v12with 4specs and no one else can join and no one can take the 2 slots on the first team even if they have a reserved slot.
I've also had the other night 13vs12 + 3 specs (total match players 25 which should mean the server is running unranked as ns2large and not ns2 ranked)

so somewhere along the lines the res slots are moving in and out of the spec slots.

things on my server that could move players into the spec slots are 

1. The Shuffle (voted by players and also admins use !enablerandom + i am immune to the shuffle)
2. The AFKkicker (which I have set to move afk to SPECTATE before they get kicked)
3. Admins team switching a player

Ipersonally think there is something in the afk switch to SPECTATE code that is not removing the reserved slot permission from the players as they go afk.

**Comment by Person8880** [comment]
The spectator/player/reserved team restrictions are handled entirely by NS2. The reserved slot plugin only tells it how many player slots are currently reserved and who has access to them, so if there's a problem switching teams it's likely an issue in the game's code.

One thing that I did see was that spectator clients could be counted as using a reserved slot if you have `TakeSlotInstantly = true`, but that wouldn't prevent players from switching teams, it would do the opposite and allow players into reserved player slots incorrectly. This will be fixed in the next update.

The next update will also have a new utility command in `basecommands` called `sh_slotsummary` which will print a summary of which slots are in use to the console. May be useful to understand exactly why it's behaving strangely.

**Comment by fazmond** [comment]
ok thanx ive tried my hardest to get the devs to look at this.
that command would help a lot to bug fix thanx thanx

**Comment by fazmond** [comment]
and your 100% sure is not the afk move to spectate that's not causing it ?

**Comment by fazmond** [comment]
or what about when a player is immune to shuffle how does this effect it ?
also ive added you on steam m8 if you wanna chat I wont pester you I promis :P

**Comment by Person8880** [comment]
Moving players goes through NS2's team switching code, so there's no real difference between the AFK plugin moving someone and someone walking into the spectator door. Being immune to shuffle also wouldn't make any difference, as it also just uses NS2's team switching.
