### ISSUE TITLE
Badge Plugin: Force custom badge to display for specific groups

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#691]
Hey Person8880

I have defined in my UserConfig groups such as "Stackers" "UnstuckAbusers", or "Trolls" etc. I also made custom badges for them so people can better identify them. Now the problem ofc is that those players just can remove the badges which is not optimally.

Is there a way to force certain custom badges on specific groups to always display?

**Comment by fazmond** [comment]
+1

**Comment by Person8880** [comment]
In the next update, declaring a `ForcedBadges` entry in either a user or a group will force those badges to be assigned to any player in the group/the specific user.

For example, this would force badge 5 to be "troll":
```json
{
    "ForcedBadges": {
        "5": "troll"
    }
}
```

Alternatively you can use a list, which will start at badge 1 onwards:
```json
{
    "ForcedBadges": [ "troll", "stacker" ]
}
```

Note that due to the awkward column system badges use, the first badge encountered for a given column will be used in preference to any inherited badge (with precedence being user entry -> user group -> inherited groups). For this reason, it's better to use the first example if inheriting, otherwise inherited lists will have their first entries ignored.
