### ISSUE TITLE
Add an option to ignore commander hive skill when shuffling

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#692]
It would be nice to ignore a commander's hive skill when shuffling. A lot of users view the impact of a 4000 hive skill commander to not be worth the hive skill they contribute to their team. Currently, users are doing the following to work around this:

> I ask another player to comm against me, and we shuffle teams first while we wait in spec, and then join teams so that field players are even

Thanks!

**Comment by GhoulofGSG9** [comment]
Doesn't `IgnoreCommanders` set to true already do that?

**Comment by TheRealNin** [comment]
The commander skill is still taken into account when shuffling even with `IgnoreCommanders` set to true.

**Comment by Person8880** [comment]
I'm not sure this makes sense. Hive is a measure of how much a player wins. Those wins can come from anything, be it commanding, field play, different life forms, different weapons and so on.

There's not enough information in the "skill" value to know whether the player will be impactful as a commander or not. Starting to second guess the skill system will just lead to lots of complexity in the shuffling system for no real gain.

**Comment by GhoulofGSG9** [comment]
Often the player's hive skill value doesn't reflect their impact on the outcome of the round as commander because they only spent a minor share of the playtime as commander. So currently the teams can end up rather uneven after a shuffle due to one commander having a skill value significantly above the average. And it may be better to just ignore the commanders and only balance out the field players.

**Comment by Person8880** [comment]
That's still an assumption that can't be validated from the skill value. One would expect a high skill player to be at least above-average at commanding purely from knowing the game well enough to know what to build. Sure they may not be as good as a player that plays commander more, but that's not something the skill value can express.

There are many similar cases, for example, a player's wins may be all from playing one team, yet the system can't know that. They may also be really good at a certain Marine build, or a certain Alien lifeform, and if they don't get it then they play way below their skill. None of this is predictable nor can it be assumed.

There's also numerous awkward problems that arise from this exception:
* Commanders changing after a shuffle, which could immediately throw the skill values way off.
* Commanders not actually chosen when the shuffle occurs. There would have to be another shuffle when commanders are chosen, and people would have to know that (and thus add to the shuffle spam).
* NS2+'s average skill output doesn't ignore commanders, so that would be confusing players with an average that's different to the one derived from ignoring commanders. I'm not keen on overriding another mod's behaviour to account for it.

**Comment by TheRealNin** [comment]
This features is just to make it easier for players who are already doing the shuffle-without-commanders. As explained in the original post, commanders are already going to ready room, shuffling, and then joining their teams before a game. This would practically just automate that process for them and make things easier.
To address your concerns:
- Players use the tournament mode and require commanders to type "ready" in chat.
- Shuffling without all players joining teams or getting loaded on the server is already a problem, and this wouldn't exactly make it worse.
- A patch could be made for NS2+, and modding or forking NS2+ is also very easy. It would be almost useless without the shuffle system supporting an "ignore commanders" score, of course.
