### ISSUE TITLE
[PreGame ] [Bug] [Low Priority] - Reloading guns in pregame

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#704]
So I use the setting "AllowAttackPreGame":false, and it works as intended but it behaves quite weird with reloading:

If you use the normal Rifle and spam leftclick, you can press R to reload and it does the sound of reloading allthough it never reloads ofc.

The pistol however, if you spam leftclick fast enough (or use a macro like probably most competitives), and you press R to reload, it actually does the reload animation.

Nothing crucial to fix, just found it out recently.

Regards

**Comment by Person8880** [comment]
This is due to Shine not overriding the appropriate method in the prediction + client VMs, so the game is predicting ammo usage and the ability to reload before the server has denied the ammo change.

It would be possible to override it, but it would be a fair bit of work to get plugins to be able to load in the prediction VM.
