### ISSUE TITLE
[Suggestion] [BaseCommands] - Change the amount of eject votes depending on the game length

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#709]
I would like to change the amount of eject votes depending on how much time passed in the round.
The times when the amount of votes changes should be configurable by the server operator.

Further I was thinking to also change the amount of eject votes for in-game replacement commanders but I can't find a nice solution. The idea here would also be that they start usually with a lower amount of votes needed.

**Comment by Person8880** [comment]
I've implemented this slightly differently. It's based on the total time a commander has spent in the command chair for the current round, rather than the round's current length. This means a different commander jumping in mid-round will start from 0.

To configure, add entries to the `EjectVotesNeeded` list:
```json
"EjectVotesNeeded": [
    {
        "FractionOfTeamToPass": 0.5, "MaxSecondsAsCommander": 30
    },
    {
        "FractionOfTeamToPass": 0.75
    }
]
```

The `MaxSecondsAsCommander` decides how long the given entry lasts. You can have as many entries as you want, and should order them by the `MaxSecondsAsCommander` in ascending order (though the plugin will correct it if you don't). The final entry should omit this so it covers the entire remaining duration (the plugin will validate and correct this if it doesn't).
