### ISSUE TITLE
Broken Custom Badges after latest bug fix push

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#742]
Re: https://github.com/Person8880/Shine/issues/741

I believe after this fix, custom badge functionality broke. No error messages appear to be popping up in the logs, so I can't really be any more specific other than "They're not showing up when we try to pick our badges".

If there's anything you can think of that I can provide that would help you troubleshoot this issue, please let me know.

**Comment by Rusty01** [comment]
Confirmed, badges are no longer functioning. Also in baseConfig.json there is "badges" as well as "Badges". Even using a vanilla baseConfig.json fails to function. If I try and enable them in game via admin menu, it says plugin loaded successfully however the icon stays yellow instead of the green checkmark showing you it's enabled. 

There is nothing in the log file that's out of the ordinary.
[16:42:53]Plugin 'Badges' loaded successfully.
[16:42:53]|-DMD-| Rusty ran command sh_loadplugin with arguments: Badges true
[16:42:54]Plugin 'Badges' loaded successfully.

Thank you again for all the work you put into Shine, :)

**Comment by Person8880** [comment]
Looks like the file name casing was incorrect in the last upload. I've re-uploaded it with the proper lower case name which should hopefully fix it.
