### ISSUE TITLE
Map vote overrides round start

### ISSUE THREAD

**Issue by MathieuHalley** [Person8880/Shine#747]
A bug/unexpected interaction between map vote & round start
Current behaviour
1. A map vote (choosing maps) was active during the pregame
2. The map vote finished half way through the countdown to the start of the round
3. The round began & was playable
4. The map changed during the round

This meant that although the round was able to start, the players had no reason to do anything because the map was about to change.

Expected behaviour
- The start of a round cancels any active map votes (both the initial vote and the following vote on which map to change to)
or
- The round can't begin while a map vote (choosing maps) is active.

**Comment by Person8880** [comment]
This is fixed in the next update by the latter method of blocking a round from starting if a player-initiated vote starts before the round does.

It will not however cancel a round that is starting right as the map vote does, as the vote can fail if not enough players vote. In this case I think it's better for the round to be left to continue as normal in case the vote fails, rather than having it reset.
