### ISSUE TITLE
Missing "sh_votemenu" Binding Still Say "M"

### ISSUE THREAD

**Issue by Deantwo** [Person8880/Shine#755]
I changed my bindings so `M` was used to request medpack. This left me unable to open the `sh_votemenu` at all (unless I was commander).

During a map vote the message still said to "press `M`" to vote. It should probably detect there is no key binding and say "(no binding)" or something instead.
Even better if it tells you the console command to use to set a new binding.

Work around: Bind a new key to `sh_votemenu` 
with a consolee command.
```
bind P sh_votemenu
```

After binding the menu to `P` it correctly says "press `P` to vote".

**Comment by Person8880** [comment]
This is because of the questionable binding system in NS2, where there are in fact 2 binding systems. The first is for gameplay input and set in the menu, the second is for binding console commands to keys using the `bind` command.

When either system binds a key, it doesn't notify the other, so keys can happily conflict. Even worse, the menu binds only sometimes stop the console binds from running, so you can end up with keys that run both binds. Requesting medpack just happens to suppress the key press before it reaches the console binds.

I can update the bind detection logic to consider any key bound in the menu and to the votemenu command as not actually bound to the votemenu and display a warning about conflicting binds if they exist.

**Comment by Deantwo** [comment]
Might be useful yeah. Maybe also report this as a bug in the NS2's tracker then.

I did notice that pressing `M` while in an exosuit opened the `sh_votemenu` too.
