### ISSUE TITLE
[BUG] wonitor skill graph

### ISSUE THREAD

**Issue by Dreyal** [Person8880/Shine#762]
The skill graph in the wonitor doesnt calculate hiveskill right once player leave or join teams mid game.
For example aliens change a player, then marines skill graph gets increased or decreased too.
https://imgur.com/a/HM9U49r

This leads to many people claiming the match was unbalanced, even though the actual skill was fair.

**Comment by Person8880** [comment]
I think you're actually looking at the NS2+ end of round stats graph, not something from Wonitor. You'll need to report the issue here:
https://github.com/NS2CDT/NS2Plus

Also, I'm not the author of Wonitor, so if there is a problem with it you'll need to report it here:
https://github.com/eBrute/wonitor
