### ISSUE TITLE
Request: Permission to upload older versions of Shine to Steam Workshop

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#766]
When using older versions of the NS2 codebase to get classic mods to work (like faded) or just to play the older versions of gameplay, it would be very useful if we could have shine running. As it currently stands, I don't know if I am able to distribute older versions of shine along with these older builds of  NS2, so I am asking permission to do so in these limited ways.

Thanks!

**Comment by Person8880** [comment]
I would expect there to be few errors running the latest version with older builds of the game or older mods. The methods Shine hooks into are either not gameplay related, or haven't changed in a very long time. Also, given you'll be using the newest engine still, there's no danger of missing engine functions.

I can see that there was an attempt to use the faded gamemode which resulted in errors in the chatbox due to an out of date `GUIChat`. An easy fix would be to update `GUIChat` to the latest version as it's fairly self contained. I don't think using an older version of Shine would be a good solution, as it'll require older configuration files (especially a problem for clients as there's no way to segregate the config like on the server) and be missing many bug fixes.

**Comment by TheRealNin** [comment]
Well then perhaps I could fork an older version of shine to use different config directories on both server and client. 

Would that be acceptable?

**Comment by Person8880** [comment]
The point I'm trying to make is that there shouldn't be any need to use older versions. The current version should work with old mods/builds with only a few small fixes required at most.

**Comment by TheRealNin** [comment]
So you would suggest that I fix all the past builds, as well as all the mods that depend on that code (whichever they are, if they exist)?

I may have to create some sort of patching program if I plan on doing many more of these. People were requesting build 249 and earlier.

**Comment by Person8880** [comment]
I can't speak for other mods, but you could just make a PR or report any issues you have with these old mods and Shine so they can be fixed. I've already added a fix for the chatbox issue faded was hitting (though it's not released yet).

**Comment by TheRealNin** [comment]
Thanks. A lot of these old mods are not being worked on anymore and I would just like to get them in a place where people can run them on servers. NS2 is basically not usable without Shine.
