### ISSUE TITLE
Occassional 11v9 Shuffles

### ISSUE THREAD

**Issue by tkdavies525** [Person8880/Shine#797]
Hello,

Shine will occasionally shuffle a 10v10 server as 11v9. Not entirely sure what's causing it, I was told this was fixed a while ago. It doesn't happen often, but when it does it's pretty jarring to players and myself. I've triple checked every setting for vote random and cannot pinpoint what might be causing this relatively rare (but still possible) 11v9 shuffle - perhaps it's a bug?

**Comment by Person8880** [comment]
Are you running any other mods that may try to block players from joining teams? In the past bad plugins have interfered with team joins and prevented the shuffle process from being able to assign a player to a team correctly. I have attempted to prevent this in the past, but it could still be an issue.

Also, it would be useful to enable debug logging for the `voterandom` plugin and see what team composition it logs when teams end up uneven. That way, if the log shows the teams are even (should be logged as a message starting with `Assigned team members:`), then it's definitely a problem when changing player teams, rather than in the teams the shuffle logic is creating.

**Comment by tkdavies525** [comment]
I'll do that. Would I enable `DebugLogging` directly from `BaseConfig.json`? Or is it appropriate to enable that somewhere else/in a different way?

**Comment by Person8880** [comment]
You'll need to set `LogLevel` to `"DEBUG"` in the plugin's config file (or use `sh_setloglevel voterandom debug` in the console).

**Comment by lumberbeard** [comment]
Seeing this quite a bit on multiple servers with different setups from Pig Pen to Neonblu.  Would like to see further interest in this one. - Lord T

**Comment by Person8880** [comment]
Without debug logs and more information about other mods that are running there's not much that can be done. There's nothing obviously wrong in the code that would cause imbalanced teams, and there's an automated report that triggers if teams are imbalanced after a shuffle which hasn't happened in a long time.

The only lead I did find was the Epsilon package's Hive team restrictions plugin which could cause imbalanced teams when someone had been forced onto a team to avoid the restriction, but that's since been fixed.

**Comment by Person8880** [comment]
As far as I know, this no longer occurs as there have bee no automated team imbalance error reports in a very long time.
