### ISSUE TITLE
optimization: userConfig

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#806]
Hi, I wanted to not clutter the other thread.
Just a question in regards to the userConfig.json. I have mine set to get from web. It is 1.5MB and growing which is quite large. I have it setup as the following... Is there a way to better optimize this? As you can imagine it is quite large as each of the 9 badge slots has a selection of 140 options. Meaning the file is 50,000 lines on the server itself. Many times I add new badges in but they do not show up in game no matter where I position them within the list of 140. (although at times they do show if I move them to the front of the list) Also the badges seem to appear in users clients as an option even if the badge name is not in the list ( indexing issue? ). I'm not sure if I am exceeding the limitations of the badge system. (note in the games badge selection menu, you only see one copy of each badge). I was thinking of cutting them up and having 20 options per slot instead of all 140.

           "12345": {
            "Group": "users",
            "Name": "bob",
            "Badges": {
            "1": [ "badge1, badge2..............badge 140" ],
            "2": [ ""badge1, badge2..............badge 140"],
            "3": [ ""badge1, badge2..............badge 140"] ],
            all the way to 9.

**Comment by Person8880** [comment]
If your example means you're assigning badges per user, you can easily remove loads of duplication simply by moving badges to groups instead. All users in a group gain access to the badges defined in it.

Another part of this is a problem with the current badge system having the notion of column-assigned badges instead of just letting users pick from a pool of badges. The badges plugin supports a [master badges table](https://github.com/Person8880/Shine/wiki/Badges#using-a-master-table), which you could use to basically do the whole 9 lists of badges once in the file, then just assign the badges in one list per group.

There's a few code-level optimisations I could implement that would also help with your use case (at least as far as badge assignment is concerned). It may explain the freezes you see sometimes if it's having to chug through a massive amount of badges each time the user file is reloaded.

**Comment by Rusty01** [comment]
Anything you could do would be a great help and is highly appreciated.
So for the master badges table. Correct me if I'm wrong as I'm just trying to see how the userConfig should look. Is this what you mean? ( I know you've got an example in the Badges plugin page but the implementation context I'm not 100% understanding - When reading your example snippet under the master table on the badges plugin page, I'm unclear as to how the "Badges" table plays into the "Groups" table if that makes sense. ). If you could make me a sample userConfig with the badges pool that would be a massive help. Thanks!

**Comment by Person8880** [comment]
The master table determines the default column(s) a given badge is added to if a user/group only provides a single badge or list of badges without specifying the column.

As an example, the following would make `badge1` and `badge2` be assigned to all columns for all users in the `ExampleGroup` group (as both badges are in all columns in the master lookup, and the group only lists badges without a column):
```json
{
	"Badges": {
		"1": [ "badge1", "badge2" ],
		"2": [ "badge1", "badge2" ],
		"3": [ "badge1", "badge2" ],
		"4": [ "badge1", "badge2" ],
		"5": [ "badge1", "badge2" ],
		"6": [ "badge1", "badge2" ],
		"7": [ "badge1", "badge2" ],
		"8": [ "badge1", "badge2" ],
		"9": [ "badge1", "badge2" ],
		"10": [ "badge1", "badge2" ]
	},
	"Groups": {
		"ExampleGroup": {
			"Badges": [ "badge1", "badge2" ]
		}
	},
	"Users": {
		"12345": {
			"Group": "ExampleGroup"
		}
	}
}
```

**Comment by Rusty01** [comment]
Ok excellent. Thank you!
