### ISSUE TITLE
Another issue with v319

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#817]
Sorry to disturb again. I think there is a critical problem with shine that prevents players from joining the server. When I try joining my server it says:

[ 42.363] Worker 11 : Error: Consistency checking failed on file 'lua/shine/lib/objects/rate_limiter.lua'

But there was no shine update today so I am confused why this error is now there and yesterday it worked fine after the hotfix.

**Comment by Person8880** [comment]
Do you have a workshop backup server setup? It could be serving an out of date version, though that file in particular hasn't changed in nearly 2 years.

Alternatively it could be that the files on the server or client have become corrupt. Is this happening to all players, or only a few of them? If it's happening to everyone, it might be that the server's files are wrong, otherwise it may be worth having the players that are getting this error clear out their mods folder.

**Comment by Wooza42** [comment]
I found out the problem. I deleted all workshop folders that got modified today and it worked.
Earlier this day I did overclock the server and did some stresstesting. The server once must have been bluescreen'd when the ns2 server was booting up.

Thanks for the help
