### ISSUE TITLE
Bug - People are moved back to readyroom after shuffle

### ISSUE THREAD

**Issue by Wooza42** [Person8880/Shine#818]
I received some reports that players that have joined a team are moved to the ready room after a successful shuffle vote. Myself can not confirm this behavior (not clear for me if those people were really not AFK) and I checked the shine log but cannot find anything relevant.

We do have now 60+ slots on the server for testing but use the enforceteamsizes to keep the game 23vs23.

If there is anything I can do to help with assisting debugging this, let me know.
[log.txt](https://github.com/Person8880/Shine/files/4548273/log.txt)

**Comment by Person8880** [comment]
Either they're considered AFK, or the enforce team sizes plugin is letting more players than intended onto a team before the shuffle, then removing them when the shuffle occurs.

If you enable debug logging on the `voterandom` plugin (set `LogLevel` to `DEBUG`), you'll be able to see the initial players it considers for sorting, and the players that end up on teams after the shuffle. If they're moved because they're AFK, they won't be in the initial players or final players list, but if it's the enforce team sizes plugin, they'll be in the initial player list but not the final list.

**Comment by Wooza42** [comment]
Thanks Person8880
I forgot to enable the debug log for voterandom. I also am not 100% if what the players report is correct, I think they were AFK during the vote.
Best regards,

**Comment by Person8880** [comment]
I found one possible case where players could be incorrectly considered AFK if they joined a team but didn't move their mouse or press any movement buttons right before a shuffle occurred. This should be fixed in the update I've released today, so hopefully anything else is just people actually being AFK.
