### ISSUE TITLE
Brainstorming ideas for BalanceModule:OptimiseTeams

### ISSUE THREAD

**Issue by requilium** [Person8880/Shine#821]
I've been thinking about different ways this could work, perhaps by adding some knowledge of the game into the algorithm itself.

My initial thoughts were around well, if you had more information about what people want to play, and you have a T7 who's gonna fade and tear everything up,  you can tweak the balance to _try_ account for that.  That requires information before it happens, though.

So my current train of thought is around having larger brackets to balance around.  Perhaps using standard deviations and treating those people equally.  Or perhaps a set of rules other than say T7 = 2xT6, etcetc because I don't think that assumption is necessarily accurate.

Perhaps Shine could keep track of a player's performance during a session and use that for balance instead of their Hive ELO (without changing how that is managed).  That would try to account for your T7 who's supposed to be carrying your team but is drunk af, hah.

I'm approaching this as an unsolvable problem, however with some feedback from players maybe the average sentiment about balance could be improved.

Thoughts?

**Comment by Person8880** [comment]
If the values output by the skill system are consistently wrong (i.e. a player it says is much higher skill actually isn't), then the problem is in the skill system, not the balancing algorithm using it. I don't think it's feasible to try to second-guess the skill values when shuffling. If they can't be trusted, then there's no point trying to arbitrarily adjust them into something else as it's a case of "garbage in, garbage out". I don't know how accurate the skill values actually are, but I would assume they're the best (and likely only) source of data available.

As for adjusting based on current performance relative to the skill value, it's difficult to measure how well a player is performing in a given round as metrics based on things like KDR, score etc. aren't necessarily indicators of playing effectively. The skill is (by necessity) an average over a large period of time and accounting only for win rate, which will always have the flaw of potentially being higher or lower than a player's performance at a given moment in time. But in the long run it should settle at a reasonable approximation without rewarding things that aren't actually helpful.

I think the most impactful improvement would be to for the Hive system to expose individual team skill (and potentially commander skill) values so that the asymmetry of the game is better accounted for. Per role skills may provide further insight, but can't work without some way to force players into the role they choose and lack any historic data, so are likely to be more hassle than they're worth.

**Comment by rifuller** [comment]
Good points!

My understanding/believe is that the ELO system is designed for 1:1 matchups.  My first experience with it was in World of Warcraft arenas where it was 2v2, 3v3, and 5v5.  Since then it's been used more widely for team games such as Overwatch.  I think it needs some adaptation to be suitable for asymmetrical team games.  Do you agree with that statement?

> I think the most impactful improvement would be to for the Hive system to expose individual team skill (and potentially commander skill) values so that the asymmetry of the game is better accounted for. Per role skills may provide further insight, but can't work without some way to force players into the role they choose and lack any historic data, so are likely to be more hassle than they're worth.

Do you not have access to individual players' skill rating?  Perhaps I'm misreading your reply - the code seems to have a `Ply:GetPlayerSkill()` method but without type names I can't find its implementation.  

I do agree that adding more contextual knowledge into the skill ratings is the most impactful change.  If we were to take commander vs player, that would be something that is enforced.  IE. Shuffle requires someone to commit to commanding first, or the commander changing after shuffle immediately forces a reshuffle to maintain order.

There are other factors though that we could discuss at length but I think commander vs player is a simple start.  What control do you/we have over Hive when it comes to making schema changes?

**Comment by Person8880** [comment]
> My understanding/believe is that the ELO system is designed for 1:1 matchups.

That's my understanding too. However, Hive isn't using Elo, it's using something bespoke that's outlined here (with only the single averaged skill value available in-game):
https://moultano.wordpress.com/2014/08/04/a-skill-ranking-system-for-natural-selection-2/

> Perhaps I'm misreading your reply - do you not have access to individual players' skill rating?

Yes, but it's effectively an average over games played on both teams. What I meant (maybe I was a bit unclear) was that a more useful approach would have access to two skill values, one for all games played as a marine, and one for all games played as an alien. As the mechanics of both teams are significantly different, it's likely that these values would be significantly different for all but the best/worst players and thus give a better indication of how well they're expected to play. Sadly this data is not yet available.

Expanding to commanders would be even more useful (ending up with four skill values), though harder to use as it would require enforcing commanders.

I don't have any control over the Hive system itself, that's something that UWE manage. Having team specific skill values available was mentioned a while ago, but I haven't heard anything about it since so I'm not sure if they hit a roadblock or just haven't prioritised it.

**Comment by rifuller** [comment]
That's a very in depth article; it'll take me a while to digest.  Briefly though, it does mention separate hive skill for commanding and the potential for other factors being considered.  Does that mean the Hive service has the capability for multiple rankings for the same player but choose only to return one value?

**Comment by Person8880** [comment]
I'm not sure. The source code for Hive isn't public so only someone from the game's development team would know.

**Comment by Person8880** [comment]
The next build of the game [adds team and commander skill values](https://unknownworlds.com/ns2/introducing-hiveskill-3-0-per-team-and-commander-hiveskill-thank-you-moultano/), which will be enabled by default in the next update to Shine. Hopefully they provide an improvement to team balance, though it'll likely take some time to asses how much they've helped.
