### ISSUE TITLE
Game balance issue.

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#848]
Hi, hope you are doing well! So we have a problem and hoping you can help. We have some high level Sanji's that are in the hive when shuffle goes through, game starts and they hop out making it +1 Alien on the field and +600 Alien Elo, It's normal for them to hop out and defend etc. but the main issue is when they go lerk or fade and single handedly wipe the entire marine team / carry the entire game as commander and secure win after win.  The problem is the Hive skill is not calculating fast enough in terms of commander skill (as you can see in the image below). Now I know you have no control over Hive itself; but this problem is bad. I brought it to the devs but the reply was for us to just start comm banning. I had to make a temporary rule that stated If you are shuffled as alien commander, you can only go skulk / gorge. Problem is it's only a band-aid solution.  I have my voteRandom config setup as below but wanted to see if there is anything you can do or recommend? Some Sanji's don't hop out. So it's frustrating from a balance standpoint. The problem did not exist prior to Hive 3.0. The problem with previous hive was Sanji's if they wanted to command would get paired up with rookies on the field. Anyways let me know your thoughts. 
Thanks and stay safe!
~Rusty

```
   "BalanceModeConfig": {
        "HIVE": {
            "UseCommanderSkill": true,
            "UseTeamSkill": true    
            "BalanceMode": "HIVE",

        }

```
![20210321222058_1](https://user-images.githubusercontent.com/12983350/111944394-ec197a00-8aad-11eb-8e06-692079b08346.jpg)

**Comment by Person8880** [comment]
Other than disabling commander skill (which brings back the problems from the previous system, though at least with team specific skills to make it still better), there's not much that can be done about skill values that are way off for commanders on my end. I don't want to start second guessing the skill system as it will just make things worse in the long run.

The real fix would be for the commander skill to reflect a player's skill better. Seems like the data ought to have been started from a value based on their existing skill rather than 0, especially given the potential for relatively infrequent commanding making the value slow to update and the fact that commanders aren't excluded from field actions. But I'm going to guess that there's little appetite for a reset of these values at this point.

**Comment by moultano** [comment]
Hi, moultano here. We discussed this for a while in the discord to figure out how to improve things. The skills were actually set to be half of the player's field skill, after some bugs were fixed that were causing them not to work correctly, so that isn't the root problem. A possible solution we came to after a lot of discussion is to provide server ops an option to use half of the field skill and half of the commander skill for the alien commander when balancing teams, and I'll explain the reasoning.

When hive calculates the skill updates at the end of the round, it uses the real times that the player was in the chair and out of the chair to decide how to treat them. If they spend a lot of time out of the chair, then it will use their field skill proportionally more, and their commander skill proportionately less. (The amount each second counts exponentially decreases through the round, but the updates are all still proportional to that weighted time.) So for updating the skill values, it isn't a problem to have a player who spends some time in and some time out of it. It will treat them as partially a player and partially a commander.

The problem is that both force even teams, and shine shuffle don't do this. They can't predict whether a player will spend their time on the field or in the chair, so there's an implicit assumption that the balancing algorithms make that whoever is the commander will be the commander for the whole round. This is a reasonable assumption for the marine commander, but is probably less reasonable for the alien commander, especially at high skill levels, where the dominant meta is for the commander to hop out and play whenever there isn't something in the tech tree that needs to be addressed immediately.

So that's why we converged to this solution of blending the field skill and commander skill, specifically for the alien comm, and as a server option, not the default. On servers where this isn't the dominant meta, they'll probably want to continue to treat the commander just as a commander, the way they do today. But on servers where it's standard for the alien commander to hop out and play more on the field, it will make shine's prediction of what will make a balanced game more in line with the timings that hive will finally be using to update the skills at the end of the game. Does that make sense?

**Comment by Person8880** [comment]
Good to know the commander skills didn't start from 0. I guess the wording of treating commanders as "new players" in the blog post implied to me that they were starting from scratch.

Blending is what I would have considered too, though not without it being officially sanctioned. Are you saying that the game code will handle this blending automatically (e.g. asking for a player's commander skill will return the blended value if some server setting managed by the game is enabled), or is this something I'd have to implement?

**Comment by moultano** [comment]
Yes, that is what was implied in the blog, and that was how it was when released. There were some bugs in the initial implementation that caused it to need a reset anyways, and everyone seemed to like the idea of using existing skills to set the commander skills, so we did that instead.

This is something you would have to implement, but only in the code to shuffle the teams itself, not elsewhere, if it is used elsewhere. I don't think there would be any issue on UWE side from doing this, nothing in hive depends on the teams being balanced, or how that balance is achieved. Servers can balance teams however they want, or not balance them at all. I can double check just to be sure.

**Comment by Person8880** [comment]
I've added a `BlendAlienCommanderAndFieldSkills` option to the `HIVE` balance mode options. When enabled, alien commanders have their skill evaluated as the average of their field and commander skill. This will be available in the next update (defaulting to `false` to preserve the existing behaviour).

**Comment by Rusty01** [comment]
Ok great, thank you so much! We'll give it a try.

**Comment by Rusty01** [comment]
I just checked the Wiki and didn't see it updated there, but assuming you haven't pushed the update as the last commit was on the 27th. I'll keep checking the wiki. Thank you again for helping to resolve that balance problem :)
