### ISSUE TITLE
Hook 'JoinTeam' is not called upon a shuffle

### ISSUE THREAD

**Issue by Turbine1991** [Person8880/Shine#853]
Shuffling appears to subvert this hook.

**Comment by Person8880** [comment]
This is intentional to stop plugins from breaking the shuffle by inadvertently blocking a swap or altering the teams after the optimiser is finished, which will throw them off balance.

If you want to observe changes in player teams, use `PostJoinTeam`. If you want to alter the teams during a shuffle, use `PreShuffleOptimiseTeams` and modify the team members table passed in.

**Comment by Turbine1991** [comment]
Cheers, I'll give `PostJoinTeam` a try.
