### ISSUE TITLE
How to add a different shuffle algorithm?

### ISSUE THREAD

**Issue by ailmanki** [Person8880/Shine#869]
I tried to figure out how to add another shuffle algorithm, and it seems there should be some way todo that, without replacing lua files.
It seems I could replace or add my own here: 
https://github.com/Person8880/Shine/blob/develop/lua/shine/extensions/voterandom/team_balance.lua#L1022

But then there is this `-- If another mod has overridden the balance algorithm, tell players.`
Which makes me think I am overlooking a simple way to override it?
https://github.com/Person8880/Shine/blob/develop/lua/shine/extensions/voterandom/server.lua#L1021

This is the algorithm I want to add, it additonally checks for skewness, but also its algorithm to try different teams is different - more exhaustive, and ignores friends and happyness.
https://replit.com/@ailmanki/NS2-BOB-SHUFFLE#main.lua

**Comment by Person8880** [comment]
The shuffle plugin doesn't really support additional algorithms cleanly as it wasn't designed to. Historically mods have done various hacks to try to override it, usually replacing the function you linked using a file hook or similar. As doing so goes through the same system and appears identical to a normal shuffle, I added the check to inform players that check `sh_teamstats` that the algorithm was changed.

A cleaner way to do it would be to make a new plugin that extends the shuffle plugin so you inherit the functionality without needing to modify the original plugin. However, I can't guarantee the plugin's internal structure will necessarily remain stable in its entirety, so you'd need to limit the overrides to just what you need (i.e. the balancing algorithm and ideally the messages to make it clear it's changed).

As for the algorithm you're looking to use, I've seen at least one attempt before at using skewness (I think the mod was called "real shuffle" or something like that) and from my testing against it it always produced results where the distributions were evenly spread out, but centred around different points, i.e. standard deviation and skewness were close, but the average of one team was higher than the other. Such teams are imbalanced by definition, both have the same shape but one has a strictly superior skill level. I also attempted to add skewness to my own cost function but had similar results, which shouldn't be surprising given much of the time the skills are in a state that there's no clearly 100% fair result (e.g. due to anomalously high/low skill players).

What you've linked seems like it may have a similar problem. It's weighting skewness and standard deviation (variance) the same as average. So a result that has near identical variance and skewness with an offset mean (i.e. objectively imbalanced) could be favoured over a result that has nearly identical means but slightly more asymmetric distribution of skill around the mean (subjectively balanced though not always ideal). That's the reason why the cost function I use has the exponential denominators, where the mean's denominator grows faster. It ensures that the mean is close first, before it then optimises the deviation from it.

Of course, I'd have to run it through simulations to be sure and you seem to have some in the project. Is your data sampled from real players? Or is it generated? My testing has always generated a roughly normal distribution based on historically recorded average and standard deviation from Hive skill data that was published. I run it through 1000s of these generated teams and record cases where any of the parameters become too far apart.
