### ISSUE TITLE
Hook issue

### ISSUE THREAD

**Issue by Rusty01** [Person8880/Shine#880]
Hi Person8880, I hope you're doing well.

I have a strange issue, When I get into game and play, all is well...
The problem appears only when I tab out of game for about 5 - 10 mins and tab back in. I get a lot of console spam and a gui issue.
>> https://diamondgamers.net/logs/log-2.old.txt (50MB log sorry for not cleaning it up)
Upon checking the Stack Trace, and trying to debug the issue, I ran into something that I cannot figure out. 
>>https://pastebin.com/i05A2kBD

The Function IntialiseGorgeSkins cannot be found (notice the typo). This appears to be failing with something to do with being full screen and minimized during a map change."

I'm not sure what to do to resolve it. I spoke to a friend and he said it could be a shine issue in how the hook is being done on tabbing back in, or it could be a game issue, or it could be an issue with our custom skins mod. It's hard to know for sure, but when we look over our source it looks to be good (although not perfect). 

Any help is appreciated in finding and fixing this issue. 
Thanks!

**Comment by Person8880** [comment]
The hook error is happening on map load, and it's coming from the DMD plugin code. The hook system doesn't do anything special to cause errors, it's just reporting the error that occurred from the callback that was registered.

Your problem is likely that you have a typo in the code, it's trying to index an enum with the field `blue` (I'm assuming it's `kGorgeVariants.blue`), but that field doesn't exist. Perhaps it's supposed to be `kGorgeVariants.Blue` instead? The later errors are caused by a variant being set on a clog that doesn't have a corresponding value in `kClogModelVariants`, which makes sense if it's set to something that was supposed to be registered by your plugin but didn't because of the error at map load.
