### ISSUE TITLE
Latest update causes stuttering

### ISSUE THREAD

**Issue by SupaFred** [Person8880/Shine#893]
The latest update causes lag and stuttering on several (all?) servers. I'll supply logs later.

**Comment by SupaFred** [comment]
Client log with errors at 12:56 https://www.dropbox.com/scl/fi/9hw0yoctkfs0gbikqpqtz/log.old.txt?rlkey=htpp5im1pug1kr6uu87vd8y3v&dl=1
Server log https://www.dropbox.com/scl/fi/bv0bsjjqrqa393c78h5jl/log-Server.txt?rlkey=r4cpx0ofjgvw6n7uk69pdh3gs&dl=1

Mod was updated 12:40 server time.

**Comment by Person8880** [comment]
That is... bizarre. Apparently, something is spamming clients with a debug command's network message, and that message is failing to print an entity due to an oversight in the log message (`Log` turns all arguments into strings, the message expects the entity ID to be a number).

This seems like a bug in the prediction VM, but it's odd that I never saw it occur when testing. I would imagine the fact the pregame plugin now hooks into the prediction VM has somehow disturbed things enough to make this start happening.

I'm pushing out a symptom fix that should stop the errors, but I'm not 100% certain if that will also stop the stuttering. Worst case scenario I'll have to remove the prediction VM functionality entirely.

**Comment by Person8880** [comment]
As far as I can tell, the fix I pushed out resolved the issue. Let me know if you still see stuttering.

**Comment by SupaFred** [comment]
It seems to be working without problems now. Thanks for the quick fix and all your work on the mod during the years!
